title: Star Wars 5th Edition
description: Work in Progress
remote_theme: just-the-docs/just-the-docs
color_scheme: dark
logo: zzImages/sw5e-logo.png
aux_links:
search_enabled: true
search.rel_url: false